### ISSUE TITLE
pod  HGSegmentedPageViewController 版本不对

### ISSUE THREAD

**Issue by SUWW** [ArchLL/HGSegmentedPageViewController#5]
pod HGSegmentedPageViewController版本并没有拉取到1.3.0的，只能拉取到1.1.3的，如果指定版本会报错。请问是最新版本是1.1.3嘛？

**Comment by SUWW** [comment]
是否有属性设置滑动滚动的，我现在只需要点击标题滚动就好，手势滚动就不需要了。请问这个属性是什么

**Comment by SUWW** [comment]
[!] CocoaPods could not find compatible versions for pod "HGSegmentedPageViewController":
  In Podfile:
    HGSegmentedPageViewController (~> 1.3.0)

None of your spec sources contain a spec satisfying the dependency: `HGSegmentedPageViewController (~> 1.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by pxygold** [comment]
升级 platform :ios, '9.0'  这个能下载到 1.2.2版本 1.3.0应该需要更高

**Comment by ArchLL** [comment]
pod install --repo-update
